### ISSUE TITLE
Integrate SASS in to site workflow

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/landing#2]
This will require existing stylesheets to be refactored for best purposes. We should follow the 7-1 pattern - you can read more about it here: https://sass-guidelin.es/#the-7-1-pattern 

This will have two steps.
 - Setting up the architecture for future work using SASS
 - Refactoring existing stylesheets.

**Comment by lloan** [comment]
This has a blocker #8

**Comment by tonynguyen111997** [comment]
Issue #8 has been closed. This issue is no longer blocked.
