### ISSUE TITLE
Create detailed readme for new contributors

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/landing#3]
Depends on #1 and #2 

Once above bugs are addressed, we need a readme so that new contributors can start working. README should include at the very minimum the following:
- how to get the app running locally
- how to clone/fork
- list/sink of our custom components 
- links to resources relative to the work on this project - react/sass/nextjs/etc. 
- style guide (branding, components, fonts, etc.)

This can optionally be broken down to smaller tasks.

**Comment by tonynguyen111997** [comment]
We just finished the branding, so I'll update the README.md to include that soon.
