### ISSUE TITLE
Missing a 'staging' branch

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/landing#6]
Create a branch named 'staging' to prevent contributors from merging changes straight to master

**Comment by lloan** [comment]
@tonynguyen111997 staging and dev branch have been created to address #6

Should we get these built on Jenkins too? Debating whether it should wait until it has been refactored to use React.

**Comment by tonynguyen111997** [comment]
I think we should wait to refactor it to React first.
