### ISSUE TITLE
Remove unused CSS classes and styling

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/landing#8]
This issue is related to #2 (refactoring stylesheets) and is meant to break that issue down into smaller issues.

- Check index.html to see if certain classes in style.css are being used. If a class is not being used then please remove them.

- **Example:** Inside style.css the "location-maps" class is declared, but never used in index.html

**Comment by lloan** [comment]
@tonynguyen111997 this would definitely be helpful!
